#cloud-config

# 0) Update & upgrade the OS before installing packages
apt_update: true
apt_upgrade: true

# 1) groups & users
groups:
  - ubuntu: [root,sys]
  - hashicorp

users:
  - default
  - name: terraform
    gecos: Terraform CI user
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,admin
    lock_passwd: false
    

# 2) packages to install via apt
packages:
  - git
  - nginx
  - certbot
  - python3-certbot-nginx
  - ufw
  - golang
  # We'll install Node.js 20 via NodeSource in runcmd.
  # However, include a dummy nodejs package so apt doesn't complain—install will be replaced by NodeSource.
  - nodejs

# 3) commands to run in order on first boot
runcmd:
  # ---- Firewall setup ----
  - ufw allow 'Nginx Full'
  - ufw allow OpenSSH
  - ufw --force enable

  # ---- Node.js & NPM (via NodeSource) ----
  - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  - apt-get install -y nodejs

  # ---- Install PM2 globally ----
  - npm install -g pm2

  # ---- (Optional) Verify PM2 is installed ----
  - pm2 --version

  # ---- Set up Terraform user’s Go workspace ----
  - sudo su - terraform -c "mkdir -p /home/terraform/go && chown terraform:hashicorp /home/terraform/go"
  - sudo -i -u terraform bash -lc "export GOPATH=/home/terraform/go; go install github.com/hashicorp/learn-go-webapp-demo@latest"
  - sudo -i -u terraform curl --output-dir /home/terraform --remote-name https://raw.githubusercontent.com/hashicorp/learn-go-webapp-demo/master/index.html

  # ---- (Optional) Start NGINX so you can confirm it’s running ----
  - systemctl enable nginx
  - systemctl start nginx
